(() => {
const D = window.PLAY_DATA;
const $app = document.getElementById('app');
const STORAGE='play_guitar_state_v1';
const defaults={tab:'home', level:'foundation', completed:{}, ratings:{}, bpm:{}, streak:0, totalMin:0, weekMin:0, sessions:0, lastDate:null, onboarding:false, profile:{instrument:'electric', level:'foundation', minutes:20, goal:'allround'}, customExercises:[]};
let state = load();
let audioCtx=null, metroTimer=null, nextBeat=0, beat=0, tunerStream=null, tunerFrame=null, practiceTimer=null;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function allLessons(){return D.levels.flatMap(l=>l.modules.flatMap(m=>m.lessons.map(x=>({...x,levelId:l.id,moduleId:m.id,levelTitle:l.title,moduleTitle:m.title}))))}
function lessonById(id){return allLessons().find(x=>x.id===id)}
function pctLevel(level){const ls=level.modules.flatMap(m=>m.lessons); return Math.round(ls.filter(x=>state.completed[x.id]).length/ls.length*100)||0}
function todayKey(){return new Date().toISOString().slice(0,10)}
function updateStreak(){const t=todayKey(); if(state.lastDate===t)return; const d=new Date();d.setDate(d.getDate()-1); const y=d.toISOString().slice(0,10); state.streak=state.lastDate===y?state.streak+1:1;state.lastDate=t}
function nav(){return `<nav class="bottomnav">${[['home','⌂','Heute'],['learn','◫','Lernen'],['practice','▶','Practice'],['tools','⌘','Tools'],['progress','↗','Fortschritt']].map(([id,ic,tx])=>`<button class="navbtn ${state.tab===id?'active':''}" data-tab="${id}"><b>${ic}</b>${tx}</button>`).join('')}</nav>`}
function top(title='PLAY.',sub='Practice less randomly.') {return `<div class="topbar"><div><div class="brand">${title}</div><div class="tagline">${sub}</div></div><button class="iconbtn" data-action="settings">⚙︎</button></div>`}
function render(){let body=''; if(state.tab==='home')body=home();if(state.tab==='learn')body=learn();if(state.tab==='practice')body=practice();if(state.tab==='tools')body=tools();if(state.tab==='progress')body=progress();$app.innerHTML=`<main class="shell">${body}</main>${nav()}`;bind();if(!state.onboarding)openOnboarding()}
function nextLesson(){const level=D.levels.find(l=>l.id===state.level)||D.levels[0]; const ls=level.modules.flatMap(m=>m.lessons); return ls.find(x=>!state.completed[x.id])||allLessons().find(x=>!state.completed[x.id])||ls[0]}
function buildSession(){const mins=Number(state.profile.minutes||20);const level=D.levels.find(l=>l.id===state.level)||D.levels[0];const undone=level.modules.flatMap(m=>m.lessons).filter(x=>!state.completed[x.id]);const weak=Object.entries(state.ratings).filter(([,v])=>v==='hard').map(([id])=>lessonById(id)).filter(Boolean);let pool=[...weak,...undone,...level.modules.flatMap(m=>m.lessons)].filter((v,i,a)=>v&&a.findIndex(x=>x.id===v.id)===i);let chosen=[];let sum=0;for(const l of pool){if(chosen.length>=5)break;if(sum+l.minutes>mins+4 && chosen.length>=3)continue;chosen.push(l);sum+=l.minutes;if(sum>=mins-2)break}return chosen}
function home(){const n=nextLesson(), s=buildSession(); return `${top()}<section class="hero"><div class="eyebrow">Deine Session · ${state.profile.minutes} min</div><h1>${state.streak?`Streak ${state.streak} · `:''}${n.title}</h1><p>${n.goal}</p><button class="primary" data-action="session">▶ Session starten</button></section><div class="stats"><div class="stat"><strong>${state.streak}🔥</strong><span>Tage Streak</span></div><div class="stat"><strong>${Math.floor(state.weekMin/60)}h ${state.weekMin%60}m</strong><span>diese Woche</span></div><div class="stat"><strong>${Object.keys(state.completed).filter(k=>state.completed[k]).length}</strong><span>Skills abgeschlossen</span></div></div><div class="sectionhead"><h2>Heute sinnvoll</h2><button data-tab="practice">Alle Übungen</button></div><div class="cards">${s.slice(0,3).map((l,i)=>lessonCard(l,i+1)).join('')}</div><div class="sectionhead"><h2>Dein Lernpfad</h2><button data-tab="learn">Öffnen</button></div><div class="cards twocol">${D.levels.map(l=>`<div class="card" data-level="${l.id}"><div class="cardrow"><div class="levelno">${l.accent}</div><div class="grow"><div class="title">${l.title}</div><div class="sub">${l.subtitle}</div></div><div class="chev">›</div></div><div class="progress"><i style="width:${pctLevel(l)}%"></i></div></div>`).join('')}</div>`}
function lessonCard(l,num=''){const done=state.completed[l.id];return `<div class="card ${done?'done':''}" data-lesson="${l.id}"><div class="cardrow"><div class="cardicon">${done?'✓':num||'♪'}</div><div class="grow"><div class="title">${esc(l.title)}</div><div class="sub">${esc(l.skill)} · ${l.minutes} min${l.bpm?` · ${state.bpm[l.id]||l.bpm} BPM`:''}</div></div><div class="chev">›</div></div></div>`}
function learn(){return `${top('PLAY. lernen','Vom ersten Ton bis zur musikalischen Freiheit.')}<div class="chiprow">${D.levels.map(l=>`<button class="chip ${state.level===l.id?'active':''}" data-level="${l.id}">${l.title}</button>`).join('')}</div><div style="height:12px"></div>${D.levels.map(level=>`<section class="card level" ${state.level!==level.id?'style="display:none"':''}><div class="levelhead"><div class="levelno">${level.accent}</div><div><div class="leveltitle">${level.title}</div><div class="sub">${level.subtitle} · ${pctLevel(level)}%</div></div></div>${level.modules.map((m,i)=>`<details class="module" ${i===0?'open':''}><summary>${m.title}<span>${m.lessons.filter(x=>state.completed[x.id]).length}/${m.lessons.length} ▾</span></summary>${m.lessons.map(l=>`<div class="lesson ${state.completed[l.id]?'done':''}" data-lesson="${l.id}"><div class="lessonbadge">${state.completed[l.id]?'✓':'▶'}</div><div class="grow"><div class="title">${l.title}</div><div class="sub">${l.skill} · ${l.minutes} min</div></div><span class="chev">›</span></div>`).join('')}</details>`).join('')}</section>`).join('')}`}
function practice(){const s=buildSession();return `${top('PLAY. practice','Trainiere das, was dich wirklich weiterbringt.')}<div class="hero"><div class="eyebrow">Adaptive Auswahl</div><h1>${state.profile.minutes} Minuten. Kein Zufall.</h1><p>Schwächere Skills kommen früher zurück; sichere Inhalte werden schrittweise schwerer.</p><button class="primary" data-action="session">▶ Session starten</button></div><div class="sectionhead"><h2>Empfohlene Session</h2></div><div class="cards">${s.map((l,i)=>lessonCard(l,i+1)).join('')}</div><div class="sectionhead"><h2>Eigene Übung</h2><button data-action="addcustom">Hinzufügen</button></div><div class="cards">${state.customExercises.length?state.customExercises.map((x,i)=>`<div class="card"><div class="cardrow"><div class="cardicon">＋</div><div class="grow"><div class="title">${esc(x.title)}</div><div class="sub">${esc(x.skill)} · ${x.minutes} min</div></div><button class="iconbtn" data-delcustom="${i}">×</button></div></div>`).join(''):`<div class="card empty">Noch keine eigenen Übungen.</div>`}</div>`}
function tools(){const icons={tuner:'⌁',metronome:'♩',tempo:'↗',chords:'◇',fretboard:'⌗',timer:'◷'};return `${top('PLAY. tools','Alles fürs Üben an einem Ort.')}<div class="toolgrid">${D.tools.map(t=>`<div class="card toolcard" data-tool="${t.id}"><div class="emoji">${icons[t.id]}</div><div><div class="title">${t.title}</div><div class="sub">${t.subtitle}</div></div></div>`).join('')}</div>`}
function progress(){const skills={};allLessons().forEach(l=>{skills[l.skill]=skills[l.skill]||{all:0,done:0};skills[l.skill].all++;if(state.completed[l.id])skills[l.skill].done++});return `${top('PLAY. progress','Fortschritt, der echte Fähigkeiten abbildet.')}<div class="stats"><div class="stat"><strong>${state.sessions}</strong><span>Sessions</span></div><div class="stat"><strong>${state.totalMin}m</strong><span>Gesamtzeit</span></div><div class="stat"><strong>${Object.values(state.ratings).filter(x=>x==='easy').length}</strong><span>Leicht-Bewertungen</span></div></div><div class="sectionhead"><h2>Skill Map</h2></div><div class="card">${Object.entries(skills).map(([k,v])=>{const p=Math.round(v.done/v.all*100)||0;return `<div class="skillrow"><div class="skilltop"><span>${k}</span><span>${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div></div>`}).join('')}</div><div class="sectionhead"><h2>Levels</h2></div><div class="cards">${D.levels.map(l=>`<div class="card"><div class="cardrow"><div class="levelno">${l.accent}</div><div class="grow"><div class="title">${l.title}</div><div class="sub">${pctLevel(l)}% abgeschlossen</div></div></div><div class="progress"><i style="width:${pctLevel(l)}%"></i></div></div>`).join('')}</div>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{state.level=b.dataset.level;state.tab=b.closest('.bottomnav')?state.tab:'learn';save();render()});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));document.querySelector('[data-action="settings"]')?.addEventListener('click',openSettings);document.querySelectorAll('[data-action="session"]').forEach(b=>b.onclick=openSession);document.querySelector('[data-action="addcustom"]')?.addEventListener('click',addCustom);document.querySelectorAll('[data-delcustom]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.customExercises.splice(+b.dataset.delcustom,1);save();render()});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool))}
function sheet(content){const d=document.createElement('div');d.className='sheet';d.innerHTML=`<div class="sheetpanel"><div class="handle"></div>${content}</div>`;d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-close]')){cleanupAudio();d.remove()}});document.body.appendChild(d);return d}
function openLesson(id){const l=lessonById(id);if(!l)return;const current=state.bpm[id]||l.bpm;const s=sheet(`<div class="sheethead"><div><div class="biglabel">${l.levelTitle||''} · ${l.skill}</div><h2>${esc(l.title)}</h2></div><button class="close" data-close>×</button></div><div class="lessonview"><p class="goal">${esc(l.goal)}</p>${l.steps?`<div class="card">${l.steps.map((x,i)=>`<div class="sessionitem"><div class="num">${i+1}</div><div>${esc(x)}</div></div>`).join('')}</div>`:''}${l.tab?`<div class="tab">${esc(l.tab)}</div>`:''}${l.progression?`<div class="chiprow">${l.progression.map(x=>`<span class="chip active">${x}</span>`).join('')}</div>`:''}${l.bpm?`<div class="card toolbox"><div class="sub">Arbeits-Tempo</div><div class="bpm" id="lessonBpm">${current}</div><div class="controls"><button class="roundbtn" data-bpm="-5">−</button><button class="primary dark" data-mini-metro>♩ Start</button><button class="roundbtn" data-bpm="5">＋</button></div></div>`:''}<div class="success"><strong>Ziel</strong><div class="sub">${esc(l.success)}</div></div><button class="primary dark full" data-complete>${state.completed[id]?'✓ Erledigt':'Als erledigt markieren'}</button><div class="rating"><button class="hard" data-rate="hard">Schwer</button><button class="good" data-rate="good">Gut</button><button class="easy" data-rate="easy">Leicht</button></div></div>`);s.querySelectorAll('[data-bpm]').forEach(b=>b.onclick=()=>{state.bpm[id]=Math.max(30,Math.min(240,(state.bpm[id]||l.bpm)+Number(b.dataset.bpm)));save();s.querySelector('#lessonBpm').textContent=state.bpm[id]});s.querySelector('[data-mini-metro]')?.addEventListener('click',e=>toggleMetronome(state.bpm[id]||l.bpm,e.currentTarget));s.querySelector('[data-complete]').onclick=()=>{state.completed[id]=true;updateStreak();state.totalMin+=l.minutes;state.weekMin+=l.minutes;save();s.remove();cleanupAudio();render()};s.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{state.ratings[id]=b.dataset.rate;if(l.bpm){const cur=state.bpm[id]||l.bpm;if(b.dataset.rate==='easy')state.bpm[id]=cur+5; if(b.dataset.rate==='hard')state.bpm[id]=Math.max(30,cur-5)}save();b.textContent='✓ '+b.textContent})}
function openSession(){const ls=buildSession();const s=sheet(`<div class="sheethead"><div><div class="biglabel">Heute</div><h2>Deine ${state.profile.minutes}-Minuten-Session</h2></div><button class="close" data-close>×</button></div><div class="card">${ls.map((l,i)=>`<div class="sessionitem" data-sessionlesson="${l.id}"><div class="num">${i+1}</div><div class="grow"><div class="title">${l.title}</div><div class="sub">${l.skill} · ${l.minutes} min</div></div><span>›</span></div>`).join('')}</div><button class="primary dark full" data-finishsession>Session abschließen</button>`);s.querySelectorAll('[data-sessionlesson]').forEach(x=>x.onclick=()=>openLesson(x.dataset.sessionlesson));s.querySelector('[data-finishsession]').onclick=()=>{state.sessions++;state.totalMin+=Number(state.profile.minutes);state.weekMin+=Number(state.profile.minutes);updateStreak();save();s.remove();render()}}
function openSettings(){const s=sheet(`<div class="sheethead"><div><div class="biglabel">Profil</div><h2>Practice Setup</h2></div><button class="close" data-close>×</button></div><div class="card"><label class="sub">Instrument</label><div class="seg" style="margin:8px 0 16px"><button data-inst="electric" class="${state.profile.instrument==='electric'?'active':''}">E-Gitarre</button><button data-inst="acoustic" class="${state.profile.instrument==='acoustic'?'active':''}">Akustik</button><button data-inst="both" class="${state.profile.instrument==='both'?'active':''}">Beides</button></div><label class="sub">Tägliche Übungszeit</label><select class="input" id="mins"><option>10</option><option>15</option><option>20</option><option>30</option><option>45</option><option>60</option></select><div style="height:14px"></div><label class="sub">Aktuelles Level</label><select class="input" id="level">${D.levels.map(l=>`<option value="${l.id}">${l.title}</option>`).join('')}</select><div style="height:16px"></div><button class="primary dark full" data-save-settings>Speichern</button></div><div class="card" style="margin-top:12px"><button class="secondary full" data-export>Backup exportieren</button><div style="height:8px"></div><button class="secondary full" data-reset>Fortschritt zurücksetzen</button></div>`);s.querySelector('#mins').value=state.profile.minutes;s.querySelector('#level').value=state.level;s.querySelectorAll('[data-inst]').forEach(b=>b.onclick=()=>{state.profile.instrument=b.dataset.inst;s.querySelectorAll('[data-inst]').forEach(x=>x.classList.toggle('active',x===b))});s.querySelector('[data-save-settings]').onclick=()=>{state.profile.minutes=+s.querySelector('#mins').value;state.level=s.querySelector('#level').value;save();s.remove();render()};s.querySelector('[data-export]').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='play-guitar-backup.json';a.click();URL.revokeObjectURL(a.href)};s.querySelector('[data-reset]').onclick=()=>{if(confirm('Fortschritt wirklich zurücksetzen?')){state={...defaults,onboarding:true,profile:{...defaults.profile}};save();s.remove();render()}}}
function openOnboarding(){const s=sheet(`<div class="sheethead"><div><div class="biglabel">Willkommen</div><h2>Was willst du spielen?</h2></div></div><p class="goal">Die App baut daraus deine täglichen Sessions. Alles kann später geändert werden.</p><div class="card"><label class="sub">Instrument</label><div class="seg" style="margin:8px 0 16px"><button data-inst="electric" class="active">E-Gitarre</button><button data-inst="acoustic">Akustik</button><button data-inst="both">Beides</button></div><label class="sub">Erfahrung</label><select class="input" id="on-level"><option value="foundation">Noch ganz am Anfang</option><option value="beginner">Grundakkorde vorhanden</option><option value="intermediate">Schon sicherer Spieler</option><option value="advanced">Fortgeschritten</option></select><div style="height:14px"></div><label class="sub">Zeit pro Session</label><select class="input" id="on-mins"><option>10</option><option>15</option><option selected>20</option><option>30</option><option>45</option></select><div style="height:18px"></div><button class="primary dark full" data-start>PLAY.</button></div>`);s.querySelectorAll('[data-inst]').forEach(b=>b.onclick=()=>{state.profile.instrument=b.dataset.inst;s.querySelectorAll('[data-inst]').forEach(x=>x.classList.toggle('active',x===b))});s.querySelector('[data-start]').onclick=()=>{state.level=s.querySelector('#on-level').value;state.profile.level=state.level;state.profile.minutes=+s.querySelector('#on-mins').value;state.onboarding=true;save();s.remove();render()}}
function addCustom(){const s=sheet(`<div class="sheethead"><h2>Eigene Übung</h2><button class="close" data-close>×</button></div><div class="card"><input class="input" id="ct" placeholder="z. B. Solo sauber spielen"><div style="height:10px"></div><input class="input" id="cs" placeholder="Skill, z. B. Lead"><div style="height:10px"></div><select class="input" id="cm"><option>5</option><option selected>10</option><option>15</option><option>20</option></select><div style="height:14px"></div><button class="primary dark full" data-add>Hinzufügen</button></div>`);s.querySelector('[data-add]').onclick=()=>{const title=s.querySelector('#ct').value.trim();if(!title)return;state.customExercises.push({title,skill:s.querySelector('#cs').value.trim()||'Eigene Übung',minutes:+s.querySelector('#cm').value});save();s.remove();render()}}
function openTool(id){if(id==='metronome')return metronomeTool();if(id==='tuner')return tunerTool();if(id==='tempo')return tempoTool();if(id==='chords')return chordsTool();if(id==='fretboard')return fretboardTool();if(id==='timer')return timerTool()}
function metronomeTool(){let bpm=80;const s=sheet(`<div class="sheethead"><h2>Metronom</h2><button class="close" data-close>×</button></div><div class="card toolbox"><div class="pulse" id="pulse">♩</div><div class="bpm" id="bpm">80</div><div class="sub">BPM · 4/4</div><div class="controls"><button class="roundbtn" data-m="-5">−</button><button class="primary dark" id="mstart">Start</button><button class="roundbtn" data-m="5">＋</button></div></div>`);s.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{bpm=Math.max(40,Math.min(220,bpm+Number(b.dataset.m)));s.querySelector('#bpm').textContent=bpm;if(metroTimer){stopMetro();startMetro(bpm,s.querySelector('#pulse'))}});s.querySelector('#mstart').onclick=e=>toggleMetronome(bpm,e.currentTarget,s.querySelector('#pulse'))}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)(); if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function clickSound(accent=false){const ctx=ensureAudio(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=accent?1200:850;g.gain.setValueAtTime(.12,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.05);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.055)}
function startMetro(bpm,pulse){stopMetro();let interval=60000/bpm;clickSound(true);if(pulse){pulse.classList.add('flash');setTimeout(()=>pulse.classList.remove('flash'),90)}beat=1;metroTimer=setInterval(()=>{clickSound(beat%4===0);if(pulse){pulse.classList.add('flash');setTimeout(()=>pulse.classList.remove('flash'),90)}beat++},interval)}
function stopMetro(){if(metroTimer){clearInterval(metroTimer);metroTimer=null}}
function toggleMetronome(bpm,btn,pulse){if(metroTimer){stopMetro();btn.textContent=btn.dataset.miniMetro!==undefined?'♩ Start':'Start'}else{startMetro(bpm,pulse);btn.textContent='Stop'}}
function tempoTool(){let bpm=60,target=100,step=5;const s=sheet(`<div class="sheethead"><h2>Tempo Trainer</h2><button class="close" data-close>×</button></div><div class="card toolbox"><div class="sub">Start</div><div class="bpm" id="tbpm">60</div><div class="controls"><button class="roundbtn" data-t="-5">−</button><button class="primary dark" id="tstart">Start</button><button class="roundbtn" data-t="5">＋</button></div><p class="notice">Nach jedem erfolgreichen Durchgang kannst du das Tempo mit +5 BPM steigern. Ziel: sauber vor schnell.</p><button class="secondary" id="success">✓ Durchgang sauber · +5 BPM</button></div>`);s.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{bpm=Math.max(40,Math.min(220,bpm+Number(b.dataset.t)));s.querySelector('#tbpm').textContent=bpm;if(metroTimer){stopMetro();startMetro(bpm)}});s.querySelector('#tstart').onclick=e=>toggleMetronome(bpm,e.currentTarget);s.querySelector('#success').onclick=()=>{bpm=Math.min(target,bpm+step);s.querySelector('#tbpm').textContent=bpm;if(metroTimer){stopMetro();startMetro(bpm)}}}
function chordsTool(){const names=Object.keys(D.chords);const s=sheet(`<div class="sheethead"><h2>Chord Library</h2><button class="close" data-close>×</button></div><div class="chiprow">${names.map((n,i)=>`<button class="chip ${i===0?'active':''}" data-chord="${n}">${n}</button>`).join('')}</div><div class="card toolbox" style="margin-top:14px"><div class="bpm" style="font-size:54px" id="cname">C</div><div id="cshape" class="tab">${chordAscii('C')}</div><p class="notice">x = Saite nicht spielen · 0 = leer · Zahl = Bund.</p></div>`);s.querySelectorAll('[data-chord]').forEach(b=>b.onclick=()=>{s.querySelectorAll('[data-chord]').forEach(x=>x.classList.toggle('active',x===b));s.querySelector('#cname').textContent=b.dataset.chord;s.querySelector('#cshape').textContent=chordAscii(b.dataset.chord)})}
function chordAscii(n){const f=D.chords[n];return ['e','B','G','D','A','E'].map((s,i)=>`${s} | ${f[5-i]}`).join('\n')}
function fretboardTool(){const notes=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];const open=[4,11,7,2,9,4];const rows=open.map((o,si)=>{let r=`${['e','B','G','D','A','E'][si]}  `;for(let f=0;f<=12;f++)r+=`${notes[(o+f)%12].padEnd(3,' ')} `;return r}).join('\n');sheet(`<div class="sheethead"><h2>Fretboard</h2><button class="close" data-close>×</button></div><div class="tab" style="font-size:12px">${rows}</div><p class="notice">Bünde 0–12. Nutze die Ansicht zum aktiven Suchen: Wähle z. B. alle C-, F- oder Root-Töne aus dem Kopf, bevor du nachsiehst.</p>`)}
function timerTool(){let secs=300,running=false;const s=sheet(`<div class="sheethead"><h2>Practice Timer</h2><button class="close" data-close>×</button></div><div class="card toolbox"><div class="bpm" id="time">05:00</div><div class="controls"><button class="roundbtn" data-time="-60">−</button><button class="primary dark" id="pstart">Start</button><button class="roundbtn" data-time="60">＋</button></div></div>`);const draw=()=>{const m=Math.floor(secs/60),q=secs%60;s.querySelector('#time').textContent=`${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}`};s.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{if(!running){secs=Math.max(60,Math.min(3600,secs+Number(b.dataset.time)));draw()}});s.querySelector('#pstart').onclick=e=>{if(running){clearInterval(practiceTimer);practiceTimer=null;running=false;e.currentTarget.textContent='Start'}else{running=true;e.currentTarget.textContent='Pause';practiceTimer=setInterval(()=>{secs--;draw();if(secs<=0){clearInterval(practiceTimer);practiceTimer=null;running=false;e.currentTarget.textContent='Start';clickSound(true)}},1000)}}}
async function tunerTool(){const s=sheet(`<div class="sheethead"><h2>Tuner</h2><button class="close" data-close>×</button></div><div class="card toolbox"><div class="tuner-note" id="tnote">–</div><div class="cents" id="tcents">Mikrofon starten</div><div class="meter"><i class="centerMark"></i><i class="needle" id="needle"></i></div><button class="primary dark" id="tunestart">Mikrofon erlauben</button><p class="notice">Chromatischer Tuner. Für beste Ergebnisse einzelne Saite anschlagen und Hintergrundgeräusche reduzieren.</p></div>`);s.querySelector('#tunestart').onclick=async e=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});tunerStream=stream;const ctx=ensureAudio();const src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=2048;src.connect(an);e.currentTarget.textContent='Tuner aktiv';e.currentTarget.disabled=true;runTuner(an,s)}catch(err){s.querySelector('#tcents').textContent='Mikrofonzugriff nicht verfügbar.'}}}
function runTuner(an,s){const buf=new Float32Array(an.fftSize);const loop=()=>{if(!document.body.contains(s)||!tunerStream)return;an.getFloatTimeDomainData(buf);const freq=autoCorrelate(buf,ensureAudio().sampleRate);if(freq>0){const midi=69+12*Math.log2(freq/440),nearest=Math.round(midi),cents=Math.round((midi-nearest)*100),names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];s.querySelector('#tnote').textContent=names[(nearest+1200)%12];s.querySelector('#tcents').textContent=`${freq.toFixed(1)} Hz · ${cents>0?'+':''}${cents} Cent`;s.querySelector('#needle').style.left=`${Math.max(2,Math.min(98,50+cents*.8))}%`}tunerFrame=requestAnimationFrame(loop)};loop()}
function autoCorrelate(buf,sampleRate){let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);if(rms<.01)return -1;let r1=0,r2=buf.length-1,thres=.2;for(let i=0;i<buf.length/2;i++){if(Math.abs(buf[i])<thres){r1=i;break}}for(let i=1;i<buf.length/2;i++){if(Math.abs(buf[buf.length-i])<thres){r2=buf.length-i;break}}buf=buf.slice(r1,r2);const c=new Array(buf.length).fill(0);for(let i=0;i<buf.length;i++)for(let j=0;j<buf.length-i;j++)c[i]+=buf[j]*buf[j+i];let d=0;while(c[d]>c[d+1])d++;let max=-1,pos=-1;for(let i=d;i<c.length;i++)if(c[i]>max){max=c[i];pos=i}if(pos<=0)return -1;let T0=pos;const x1=c[T0-1]||c[T0],x2=c[T0],x3=c[T0+1]||c[T0],a=(x1+x3-2*x2)/2,b=(x3-x1)/2;if(a)T0=T0-b/(2*a);const f=sampleRate/T0;return f>55&&f<1400?f:-1}
function cleanupAudio(){stopMetro();if(practiceTimer){clearInterval(practiceTimer);practiceTimer=null}if(tunerFrame){cancelAnimationFrame(tunerFrame);tunerFrame=null}if(tunerStream){tunerStream.getTracks().forEach(t=>t.stop());tunerStream=null}}
window.addEventListener('beforeunload',cleanupAudio);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
})();
